### ISSUE TITLE
NullReferenceException when pressing secondary with logiX tip with extract mode set to reference node while holding a value proxy

### ISSUE THREAD

**Issue by art0007i** [badhaloninja/LogixUtils#1]
Reproduction steps
1. Set logix tip to Extract: Reference Node
2. Grab a Value Proxy (the blue texts you can grab and drop onto fields)
3. Press secondary
4. Check your log, it will have an error

This partially breaks compatibility with my mod [ValueProxyExtensions](https://github.com/art0007i/ValueProxyExtensions/)
Here is a log file of me doing this, with only the LogixUtils mod loaded
[ROTHORN - 2022.1.28.1335 - 2022-08-08 23_16_58.log](https://github.com/badhaloninja/LogixUtils/files/9285119/ROTHORN.-.2022.1.28.1335.-.2022-08-08.23_16_58.log)

**Comment by badhaloninja** [comment]
I'm not able to reproduce this?

Also you appear to be using version [v1.4.0](https://github.com/badhaloninja/LogixUtils/releases/tag/v1.4.0), the current version is [v1.5.1](https://github.com/badhaloninja/LogixUtils/releases/tag/v1.5.1)

**Comment by art0007i** [comment]
I was indeed on the wrong version, but that part of the code hasn't changed in the update and I still get the error.

Here is a video of me replicating the issue.
https://user-images.githubusercontent.com/19620451/185809219-4565b694-2760-4bf6-bc0e-d21503be7c4a.mp4

Here is a log file with this happening using the latest version of the mod.
Just `ctrl + f`  `LogixUtils`
[ROTHORN - 2022.1.28.1335 - 2022-08-21 22_13_03.log](https://github.com/badhaloninja/LogixUtils/files/9389883/ROTHORN.-.2022.1.28.1335.-.2022-08-21.22_13_03.log)

I am using default config in case that's relevant


There is nothing weird happening in game during this bug, but it does cause an exception, which prevents other prefixes on the same method from running.

**Comment by badhaloninja** [comment]
I'm able to reproduce it now, it's if any object is held that's not a reference proxy, I forgot a null check it

https://github.com/badhaloninja/LogixUtils/releases/tag/v1.5.2
this should fix it

**Comment by art0007i** [comment]
works perfectly, thank you so much
